#!/bin/sh

# Prebuilt Clang Toolchain (AOSP)
# clang 6
CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r61/clang-4691093.tar.gz"

# clang 9
# CLANG_URL=https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android10-release/clang-r353983c.tar.gz

mkdir clang ; wget $CLANG_URL  && tar -xzf *.gz -C clang/
